-- drop table if exists user cascade;
--
-- create table user
-- (
--     id         serial  not null primary key,
--     password   varchar not null,
--     username   varchar not null unique,
--     first_name varchar not null,
--     last_name  varchar not null,
--     address    varchar not null
-- );
